<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<AssemblyName>ReduxUpdater</AssemblyName>
		<RootNamespace>ReduxUpdater</RootNamespace>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>x64</Platforms>
		<Configurations>Debug;Release;Publish;PublishTest</Configurations>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<OutputPath>$(MSBuildProjectDirectory)\..\..\bin\UpdaterPayload\$(Configuration)\</OutputPath>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<DebugType>none</DebugType>
		<Optimize>true</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
	</PropertyGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="Redux.Core.Tests" />
	</ItemGroup>
</Project>
