<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net48</TargetFramework>
		<AssemblyName>Redux.Installer.Tests</AssemblyName>
		<RootNamespace>Redux.Installer.Tests</RootNamespace>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>x64</Platforms>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Installer\ReduxInstaller.csproj" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="System.IO.Compression" />
		<Reference Include="System.IO.Compression.FileSystem" />
		<Reference Include="System.Net.Http" />
	</ItemGroup>
</Project>
